[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 88

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
filterwarnings = [
    "error",
    # imp is indirectly used by uncertainties,
    # see https://github.com/lebigot/uncertainties/issues/145
    # the deprecation warning message for imp changed in Python 3.10
    # we ignore both using a wild card
    "ignore:the imp module is deprecated in favour of importlib.*:DeprecationWarning",
    # we run tests against a non-GUI backend on purpose
    "ignore:Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.:UserWarning",
    # astropy regularly ships wheels that violate numpy ABI compatibility, this is out of our control
    "ignore:numpy.ndarray size changed, may indicate binary incompatibility. Expected \\d\\d from C header, got \\d\\d from PyObject:RuntimeWarning",
]

[tool.coverage.run]
omit = [
  "amical/externals/*",
]

[tool.coverage.report]
omit = [
  "amical/externals/*",
  "amical/dpfit.py",
]

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
show_error_context = true
show_error_codes = true
