name: type checking

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "doc/**"
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build AMICAL + type check deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[typecheck]

    - name: Run mypy
      run: mypy amical
